// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChP36qUzcicPLO8a_jxYl5tectrb2tRP8',
    appId: '1:1079553396725:web:df8c428a102787bf4e5abc',
    messagingSenderId: '1079553396725',
    projectId: 'chatter-56f8c',
    authDomain: 'chatter-56f8c.firebaseapp.com',
    storageBucket: 'chatter-56f8c.appspot.com',
    measurementId: 'G-WD30K02800',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBrMfIGlkJNH0jts5O82HdeTpJC5-2kw',
    appId: '1:1079553396725:android:943d97e33185377a4e5abc',
    messagingSenderId: '1079553396725',
    projectId: 'chatter-56f8c',
    storageBucket: 'chatter-56f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbyFhS_4vsL3Jef5xPJ0OWwRyIPYKC_2Y',
    appId: '1:1079553396725:ios:48dc23470f8b45fa4e5abc',
    messagingSenderId: '1079553396725',
    projectId: 'chatter-56f8c',
    storageBucket: 'chatter-56f8c.appspot.com',
    iosClientId: '1079553396725-o27674kc6cokv0q52tflga04mldf3q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbyFhS_4vsL3Jef5xPJ0OWwRyIPYKC_2Y',
    appId: '1:1079553396725:ios:48dc23470f8b45fa4e5abc',
    messagingSenderId: '1079553396725',
    projectId: 'chatter-56f8c',
    storageBucket: 'chatter-56f8c.appspot.com',
    iosClientId: '1079553396725-o27674kc6cokv0q52tflga04mldf3q57.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatter',
  );
}
